version: '3.1'

services:
  db:
    container_name: batch-notification-mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=employees
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"